export enum MachineType {
    OFFSET_SHEETFED = 'OFFSET_SHEETFED',
    OFFSET_WEBFED = 'OFFSET_WEBFED',
    DIGITAL_TONER = 'DIGITAL_TONER',
    DIGITAL_INKJET = 'DIGITAL_INKJET',
    LARGE_FORMAT_INKJET = 'LARGE_FORMAT_INKJET',
    LARGE_FORMAT_SOLVENT = 'LARGE_FORMAT_SOLVENT',
    LARGE_FORMAT_UV = 'LARGE_FORMAT_UV',
    SCREEN_PRINT = 'SCREEN_PRINT',
    FLEXOGRAPHIC = 'FLEXOGRAPHIC',
    GRAVURE = 'GRAVURE',
    LETTERPRESS = 'LETTERPRESS',
    PAD_PRINTING = 'PAD_PRINTING',
    RISOGRAPH = 'RISOGRAPH',
    THERMOGRAPHIC = 'THERMOGRAPHIC',
    ENGRAVING = 'ENGRAVING',
    EMBOSSING_DEBOSSING = 'EMBOSSING_DEBOSSING',
    FOIL_STAMPING = 'FOIL_STAMPING',
    DIE_CUTTING = 'DIE_CUTTING',
    LAMINATING = 'LAMINATING',
    BINDING_PERFECT = 'BINDING_PERFECT',
    BINDING_SADDLE_STITCH = 'BINDING_SADDLE_STITCH',
    BINDING_CASE = 'BINDING_CASE',
    BINDING_SPIRAL = 'BINDING_SPIRAL',
    FOLDING = 'FOLDING',
    CUTTING_GUILLOTINE = 'CUTTING_GUILLOTINE',
    CREASING = 'CREASING',
    COLLATING = 'COLLATING',
    UV_COATING = 'UV_COATING',
    AQUEOUS_COATING = 'AQUEOUS_COATING',
    VARNISHING = 'VARNISHING',
    NUMBERING = 'NUMBERING',
    PERFORATING = 'PERFORATING',
    SCORING = 'SCORING',
    CUSTOM = 'CUSTOM',
}

export enum MachineStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    MAINTENANCE = 'MAINTENANCE',
    DECOMMISSIONED = 'DECOMMISSIONED',
    PENDING_INSTALLATION = 'PENDING_INSTALLATION',
}

export enum ColorMode {
    MONO = 'MONO',               // 1+0 or 1+1
    SPOT_COLOR = 'SPOT_COLOR',   // 2+0, 2+1, 2+2
    FULL_COLOR = 'FULL_COLOR',   // 4+0, 4+1, 4+4
    EXTENDED_GAMUT = 'EXTENDED_GAMUT', // 6+, 7+, 8+
    VARIABLE = 'VARIABLE',       // Digital — no fixed color config
}

export enum SpeedUnit {
    SHEETS_PER_HOUR = 'SHEETS_PER_HOUR',
    IMPRESSIONS_PER_HOUR = 'IMPRESSIONS_PER_HOUR',
    METERS_PER_MINUTE = 'METERS_PER_MINUTE',
    FEET_PER_MINUTE = 'FEET_PER_MINUTE',
    COPIES_PER_MINUTE = 'COPIES_PER_MINUTE',
    SQFT_PER_HOUR = 'SQFT_PER_HOUR',
    SQM_PER_HOUR = 'SQM_PER_HOUR',
    LINEAR_FEET_PER_MINUTE = 'LINEAR_FEET_PER_MINUTE',
}

export enum MaintenanceInterval {
    PER_JOB = 'PER_JOB',
    DAILY = 'DAILY',
    WEEKLY = 'WEEKLY',
    MONTHLY = 'MONTHLY',
    PER_IMPRESSION_COUNT = 'PER_IMPRESSION_COUNT',
    PER_OPERATING_HOURS = 'PER_OPERATING_HOURS',
}

export enum DepreciationMethod {
    STRAIGHT_LINE = 'STRAIGHT_LINE',
    DECLINING_BALANCE = 'DECLINING_BALANCE',
    SUM_OF_YEARS = 'SUM_OF_YEARS',
    UNITS_OF_PRODUCTION = 'UNITS_OF_PRODUCTION',
    NONE = 'NONE', // Fully depreciated or rented
}

export enum InkType {
    OIL_BASED = 'OIL_BASED',
    SOY_BASED = 'SOY_BASED',
    UV_CURABLE = 'UV_CURABLE',
    WATER_BASED = 'WATER_BASED',
    SOLVENT = 'SOLVENT',
    LATEX = 'LATEX',
    SUBLIMATION = 'SUBLIMATION',
    TONER_POWDER = 'TONER_POWDER',
    TONER_LIQUID = 'TONER_LIQUID',
}
